### PR TITLE
Continuation of https://github.com/ambanum/CGUs/pull/111

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
Bummer, git log shows the author date:
```sh
commit cc9a61dcdec858abe68f8ea6f19b68ecd6b8b1a5 (HEAD -> tosback-import-google, me/tosback-import-google)
Author: Michiel de Jong <michiel@unhosted.org>
Date:   Thu Jun 25 02:06:53 2020 -0400

    Google/Terms of Service.html from tosback2@81ba23f
    
    Imported from https://github.com/tosdr/tosback2/blob/81ba23f0490d71ed266ca8b6f734c961f66e3e81/crawl_reviewed/google.com/Terms of Service.txt
```
But github shows the commit date: https://github.com/michielbdejong/CGUs-snapshots/commit/cc9a61dcdec858abe68f8ea6f19b68ecd6b8b1a5

**Comment by michielbdejong** [comment]
I'll just put the author date into the first line of the commit message as well.

**Comment by michielbdejong** [comment]
Task queueing is not trivial, it should really be a tree of queues:
* one source file at a time, finish the whole history for one file before starting the next file
  * one commit at a time, finish writing to the snapshots repo before checking out the next commit at the source

I used `tosbackGitSemaphore` and `snapshotsGitSemaphore` but I should really be using `fileLevelSemaphore` and `commitLevelSemaphore`.

**Comment by michielbdejong** [comment]
ok, got the semaphores working. Will now:
* [x] URL-encode links like https://github.com/tosdr/tosback2/blob/76c5ae802cc294767909e02239f9ba8389d57a30/crawl/500px.com/Privacy
* [x] create rules example PR
* [x] create versions example PR
* [ ] incorporate any feedback from https://github.com/ambanum/CGUs-snapshots/pull/3
* [ ] incorporate any feedback from https://github.com/ambanum/CGUs/pull/113
* [ ] incorporate any feedback from https://github.com/ambanum/CGUs-versions/pull/4

**Comment by michielbdejong** [comment]
See https://github.com/ambanum/CGUs-versions/pull/4 and https://github.com/ambanum/CGUs/pull/113

**Comment by michielbdejong** [comment]
It chokes on `rules/app.net.xml` which [is commented out](https://github.com/tosdr/tosback2/blob/master/rules/app.net.xml):
```sh
Reading file /Volumes/Workspace/tosback2/crawl_reviewed/android.com/Privacy Policy.txt ea508531b9d42af5c97b040a7476c28948760c58
saving snapshot ../CGUs/data/snapshots/Android/Privacy Policy.html
committing ../CGUs/data/snapshots/Android/Privacy Policy.html From tosback2 ea508531b9d42af5c97b040a7476c28948760c58
saving version ../CGUs/data/versions/Android/Privacy Policy.md
committing ../CGUs/data/versions/Android/Privacy Policy.md From tosback2 ea508531b9d42af5c97b040a7476c28948760c58
importCrawl end android.com Privacy Policy.txt
importCrawl app.net Privacy Policy.txt App/Privacy Policy.html
filePath crawl_reviewed/app.net/Privacy Policy.txt
Tosback2 git checkout master
Tosback2 git pull
file:///Users/michiel/gh/ambanum/TOSBack-CGUs-bridge/tosback-import.js:395
  if (!Array.isArray(imported.sitename.docname)) {
                                       ^

TypeError: Cannot read property 'docname' of undefined
    at importRule (file:///Users/michiel/gh/ambanum/TOSBack-CGUs-bridge/tosback-import.js:395:40)
    at async file:///Users/michiel/gh/ambanum/TOSBack-CGUs-bridge/tosback-import.js:438:5
    at async run (/Users/michiel/gh/ambanum/TOSBack-CGUs-bridge/node_modules/p-queue/dist/index.js:159:29)

**Comment by MattiSG** [comment]
> beefy build server

🐄

Quite curious on the time it takes!

**Comment by MattiSG** [comment]
Wow! Thanks @TosbackCgusBridge-Bot 😉

**Comment by MattiSG** [comment]
Yes, sorry! We were wondering how to make that more readable / detectable. Should we notify you when there are changes? Would SemVer be better? Shall we just have a chat when needed?

**Comment by michielbdejong** [comment]
For this project it's not so important, I can just see when my script breaks and change it :)
In the future it would be nice if you could publish CGUs as an npm package with semver, but for now it's fine.

**Pull request merged**
